### ISSUE TITLE
"No such file or directory" when finishing race

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [pb4git/trackmania_rl_public#13]
``PS C:\Users\jesse\Downloads\trackmania_rl_public-main\trackmania_rl_public-main> python .\scripts\observe_manual_run_to_extract_checkpoints.py
Connecting to TMInterface0...
Registered to TMInterface0
Exception in thread Thread-1 (_main_thread):
Traceback (most recent call last):
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\site-packages\tminterface\interface.py", line 843, in _main_thread
    self._process_server_message()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\site-packages\tminterface\interface.py", line 881, in _process_server_message
    self.client.on_checkpoint_count_changed(self, current, target)
  File "C:\Users\jesse\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\observe_manual_run_to_extract_checkpoints.py", line 59, in on_checkpoint_count_changed
    self.extract_cp_distance_interval()
  File "C:\Users\jesse\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\observe_manual_run_to_extract_checkpoints.py", line 89, in extract_cp_distance_interval
    np.save(base_dir / "maps" / "map.npy", np.array(self.zone_centers).round(1))
  File "<__array_function__ internals>", line 200, in save
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 518, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jesse\\Downloads\\trackmania_rl_public-main\\trackmania_rl_public-main\\maps\\map.npy'
PS C:\Users\jesse\Downloads\trackmania_rl_public-main\trackmania_rl_public-main> python .\scripts\observe_manual_run_to_extract_checkpoints.py
Connecting to TMInterface0...
Registered to TMInterface0
Exception in thread Thread-1 (_main_thread):
Traceback (most recent call last):
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\site-packages\tminterface\interface.py", line 843, in _main_thread
    self._process_server_message()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\site-packages\tminterface\interface.py", line 881, in _process_server_message
    self.client.on_checkpoint_count_changed(self, current, target)
  File "C:\Users\jesse\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\observe_manual_run_to_extract_checkpoints.py", line 59, in on_checkpoint_count_changed
    self.extract_cp_distance_interval()
  File "C:\Users\jesse\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\observe_manual_run_to_extract_checkpoints.py", line 89, in extract_cp_distance_interval
    np.save(base_dir / "maps" / "map.npy", np.array(self.zone_centers).round(1))
  File "<__array_function__ internals>", line 200, in save
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 518, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jesse\\Downloads\\trackmania_rl_public-main\\trackmania_rl_public-main\\maps\\map.npy'``

**Comment by ThatGuyCalledJesse** [comment]
Connecting works fine but when finishing the race this message pops up in the console
